"use client";

import { useEffect, useState } from "react";
import { CheckCircle2, Clock3, FileSpreadsheet, KeyRound, RefreshCw, Save, Upload, UserPlus, UsersRound } from "lucide-react";

const defaultMapping = { externalId: "external_id", metaLeadId: "meta_lead_id", createdAt: "created_at", fullName: "name", phone: "phone", email: "email", city: "city", campaignName: "campaign", adName: "ad" };
type Mapping = typeof defaultMapping;
type SheetState = { credentialsConfigured: boolean; serviceAccountEmail: string | null; connection: null | { spreadsheet_id: string; sheet_name: string; header_row: number; import_after: string; mapping: Mapping; enabled: boolean; last_synced_at: string | null; last_error: string | null; last_skipped_rows: number }; runs: Array<{ id: string; status: string; rows_seen: number; inserted_rows: number; repeat_rows: number; rejected_rows: number; skipped_rows: number; unchanged_rows: number; started_at: string }> };
type UserRow = { id: string; display_name: string; phone_e164: string | null; email: string | null; role: "owner" | "salesperson" | "agency"; status: string };
type StoreState = { opensAt: string; closesAt: string; closedWeekdays: number[]; followupDays: number };

export function AdminConsole() {
  const [users, setUsers] = useState<UserRow[]>([]);
  const [userForm, setUserForm] = useState({ displayName: "", email: "", phone: "", role: "salesperson", temporaryPassword: "" });
  const [sheet, setSheet] = useState<SheetState | null>(null);
  const [sheetForm, setSheetForm] = useState({ spreadsheet: "", sheetName: "Leads", headerRow: 1, importAfter: "", enabled: false, mapping: defaultMapping });
  const [store, setStore] = useState<StoreState>({ opensAt: "10:30", closesAt: "20:30", closedWeekdays: [], followupDays: 4 });
  const [message, setMessage] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);

  async function load() {
    const [usersResponse, sheetResponse, storeResponse] = await Promise.all([fetch("/api/admin/users", { cache: "no-store" }), fetch("/api/integrations/google-sheets", { cache: "no-store" }), fetch("/api/settings/store-hours", { cache: "no-store" })]);
    if (usersResponse.ok) setUsers((await usersResponse.json()).users);
    if (sheetResponse.ok) { const value = await sheetResponse.json() as SheetState; setSheet(value); if (value.connection) setSheetForm({ spreadsheet: value.connection.spreadsheet_id, sheetName: value.connection.sheet_name, headerRow: value.connection.header_row, importAfter: value.connection.import_after?.slice(0,16) ?? "", enabled: value.connection.enabled, mapping: { ...defaultMapping, ...value.connection.mapping } }); }
    if (storeResponse.ok) { const value = await storeResponse.json() as StoreState; setStore({ opensAt: value.opensAt, closesAt: value.closesAt, closedWeekdays: value.closedWeekdays, followupDays: value.followupDays }); }
  }
  useEffect(() => { void load(); }, []);

  async function addUser(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const response = await fetch("/api/admin/users", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(userForm) }); const value = await response.json() as { error?: string }; setMessage(response.ok ? "User created. They must change the temporary password." : value.error ?? "Could not create user"); if (response.ok) { setUserForm({ displayName: "", email: "", phone: "", role: "salesperson", temporaryPassword: "" }); await load(); } }
  async function updateUser(id: string, body: Record<string, unknown>) { const response = await fetch(`/api/admin/users/${id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); const value = await response.json() as { error?: string }; setMessage(response.ok ? "User updated" : value.error ?? "Could not update user"); if (response.ok) await load(); }
  async function resetPassword(id: string) { const temporaryPassword = window.prompt("Enter a temporary password (minimum 10 characters)"); if (temporaryPassword) await updateUser(id, { temporaryPassword }); }

  async function sheetAction(action: "save" | "test" | "sync") { setBusy(true); const endpoint = action === "save" ? "/api/integrations/google-sheets" : `/api/integrations/google-sheets/${action}`; const payload = { ...sheetForm, importAfter: sheetForm.importAfter ? new Date(sheetForm.importAfter).toISOString() : undefined }; const response = await fetch(endpoint, { method: action === "save" ? "PUT" : "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); const value = await response.json() as Record<string, unknown>; setMessage(response.ok ? action === "test" ? `Connected: ${value.rowCount} rows found.` : action === "sync" ? `${value.inserted} new, ${value.repeats} repeats, ${value.unchanged} unchanged, ${value.skipped} skipped.` : "Google Sheet settings saved" : String(value.error ?? "Google Sheet action failed")); setBusy(false); if (response.ok) await load(); }
  async function saveStore(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const response = await fetch("/api/settings/store-hours", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify(store) }); const value = await response.json() as { error?: string }; setMessage(response.ok ? "Store hours and cadence saved" : value.error ?? "Could not save hours"); }
  async function importCsv(file?: File) { if (!file) return; const body = new FormData(); body.set("file", file); const response = await fetch("/api/imports/csv", { method: "POST", body }); const value = await response.json(); setMessage(response.ok ? `${value.inserted ?? value.valid ?? 0} leads imported or validated.` : value.error); }

  return <div className="admin-grid">
    {message && <button className="admin-message" onClick={() => setMessage(null)}><CheckCircle2 />{message}</button>}
    <section className="panel admin-card wide users-card"><header><UsersRound /><div><h2>Users and roles</h2><p>Owner, salesperson and read-only agency access</p></div><span className="healthy-tag">{users.filter((item) => item.status === "active").length} active</span></header>
      <form className="user-create-form" onSubmit={addUser}><label>Name<input required minLength={2} value={userForm.displayName} onChange={(event) => setUserForm({ ...userForm, displayName: event.target.value })} /></label><label>Email<input required type="email" value={userForm.email} onChange={(event) => setUserForm({ ...userForm, email: event.target.value })} /></label><label>Phone (optional)<input value={userForm.phone} onChange={(event) => setUserForm({ ...userForm, phone: event.target.value })} /></label><label>Role<select value={userForm.role} onChange={(event) => setUserForm({ ...userForm, role: event.target.value })}><option value="salesperson">Salesperson</option><option value="owner">Owner</option><option value="agency">Agency viewer</option></select></label><label>Temporary password<input required type="password" minLength={10} value={userForm.temporaryPassword} onChange={(event) => setUserForm({ ...userForm, temporaryPassword: event.target.value })} /></label><button><UserPlus />Create</button></form>
      <div className="user-list">{users.map((item) => <div key={item.id}><span className="person-dot">{item.display_name[0]}</span><span><strong>{item.display_name}</strong><small>{item.role} · {item.email}</small></span><em className={item.status === "active" ? "healthy-tag" : "setup-tag"}>{item.status}</em><button onClick={() => void resetPassword(item.id)}><KeyRound size={14} />Reset password</button><button onClick={() => void updateUser(item.id, { status: item.status === "active" ? "disabled" : "active" })}>{item.status === "active" ? "Disable" : "Enable"}</button></div>)}</div>
    </section>

    <section className="panel admin-card wide"><header><Clock3 /><div><h2>Store clock and follow-ups</h2><p>One seven-day schedule; response time counts business minutes only</p></div></header><form className="store-form" onSubmit={saveStore}><label>Opens<input type="time" value={store.opensAt} onChange={(event) => setStore({ ...store, opensAt: event.target.value })} /></label><label>Closes<input type="time" value={store.closesAt} onChange={(event) => setStore({ ...store, closesAt: event.target.value })} /></label><label>Follow-up days<input type="number" min="1" max="14" value={store.followupDays} onChange={(event) => setStore({ ...store, followupDays: Number(event.target.value) })} /></label><fieldset><legend>Closed days</legend>{["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].map((day,index) => <label key={day}><input type="checkbox" checked={store.closedWeekdays.includes(index)} onChange={(event) => setStore({ ...store, closedWeekdays: event.target.checked ? [...store.closedWeekdays,index] : store.closedWeekdays.filter((value) => value !== index) })} />{day}</label>)}</fieldset><button><Save />Save schedule</button></form></section>

    <section className="panel admin-card wide sheets-card"><header><FileSpreadsheet /><div><h2>Live Google Sheet intake</h2><p>Incremental sync, periodic full check and no row limit</p></div><span className={sheet?.credentialsConfigured ? "healthy-tag" : "setup-tag"}>{sheet?.credentialsConfigured ? "Credentials ready" : "Credentials needed"}</span></header><p className="admin-note">Share the Sheet as Viewer with <strong>{sheet?.serviceAccountEmail ?? "the configured service-account email"}</strong>. The cutoff prevents historic rows from entering the live queue.</p><div className="sheet-form"><label className="wide-field">Google Sheets URL or ID<input value={sheetForm.spreadsheet} onChange={(event) => setSheetForm({ ...sheetForm, spreadsheet: event.target.value })} /></label><label>Tab<input value={sheetForm.sheetName} onChange={(event) => setSheetForm({ ...sheetForm, sheetName: event.target.value })} /></label><label>Header row<input type="number" min="1" value={sheetForm.headerRow} onChange={(event) => setSheetForm({ ...sheetForm, headerRow: Number(event.target.value) })} /></label><label>Import leads created after<input type="datetime-local" value={sheetForm.importAfter} onChange={(event) => setSheetForm({ ...sheetForm, importAfter: event.target.value })} /></label>{Object.entries(sheetForm.mapping).map(([key,value]) => <label key={key}>{key.replace(/([A-Z])/g," $1")} column<input value={value} onChange={(event) => setSheetForm({ ...sheetForm, mapping: { ...sheetForm.mapping, [key]: event.target.value } as Mapping })} /></label>)}<label className="sheet-toggle wide-field"><input type="checkbox" checked={sheetForm.enabled} onChange={(event) => setSheetForm({ ...sheetForm, enabled: event.target.checked })} />Enable automatic sync</label></div><div className="sheet-actions"><button disabled={busy} onClick={() => void sheetAction("save")}><Save />Save</button><button disabled={busy || !sheet?.credentialsConfigured} onClick={() => void sheetAction("test")}><CheckCircle2 />Test</button><button disabled={busy || !sheet?.connection?.enabled} onClick={() => void sheetAction("sync")}><RefreshCw />Sync now</button></div>{sheet?.connection && <p className="admin-note">Last sync: {sheet.connection.last_synced_at ? new Date(sheet.connection.last_synced_at).toLocaleString("en-IN") : "never"} · Last cutoff skips: {sheet.connection.last_skipped_rows}</p>}{sheet?.runs?.length ? <div className="sync-history">{sheet.runs.map((run) => <span key={run.id}>{new Date(run.started_at).toLocaleString("en-IN")} · {run.status} · {run.inserted_rows} new · {run.repeat_rows} repeat · {run.skipped_rows} skipped · {run.unchanged_rows} unchanged</span>)}</div> : null}</section>

    <section className="panel admin-card" id="imports"><header><Upload /><div><h2>CSV import</h2><p>Manual one-off intake</p></div></header><label className="upload-box"><Upload /><strong>Select CSV</strong><input type="file" accept=".csv,text/csv" onChange={(event) => void importCsv(event.target.files?.[0])} /></label></section>
  </div>;
}
