"use client";

import { useEffect, useState } from "react";
import { CheckCircle2, Clock3, FileSpreadsheet, KeyRound, Plus, Radio, RefreshCw, Save, Trash2, UserPlus, UsersRound } from "lucide-react";

const defaultMapping = { externalId: "external_id", metaLeadId: "meta_lead_id", createdAt: "created_at", fullName: "name", phone: "phone", email: "email", city: "city", campaignName: "campaign", adName: "ad" };
type Mapping = typeof defaultMapping;
type SheetState = { credentialsConfigured: boolean; enabledByEnvironment: boolean; serviceAccountEmail: string | null; connection: null | { spreadsheet_id: string; sheet_name: string; header_row: number; import_after: string; mapping: Mapping; enabled: boolean; last_synced_at: string | null; last_error: string | null; last_skipped_rows: number }; runs: Array<{ id: string; status: string; rows_seen: number; inserted_rows: number; repeat_rows: number; rejected_rows: number; skipped_rows: number; unchanged_rows: number; started_at: string }> };
type UserRow = { id: string; display_name: string; phone_e164: string | null; email: string | null; role: "owner" | "salesperson" | "agency"; status: string };
type StoreState = { opensAt: string; closesAt: string; closedWeekdays: number[]; followupDays: number };
type MetaForm = { formId: string; name: string; mapping: { fullName: string; phone: string; email: string; city: string } };
type MetaState = { enabledByEnvironment: boolean; credentialsConfigured: boolean; graphVersion: string; forms: MetaForm[]; connection: null | { last_webhook_at: string | null; last_healthy_at: string | null; last_reconciled_at: string | null; last_reconciliation_result: Record<string, unknown> } };
const newMetaForm = (): MetaForm => ({ formId: "", name: "Lead form", mapping: { fullName: "full_name", phone: "phone_number", email: "email", city: "city" } });

export function AdminConsole() {
  const [users, setUsers] = useState<UserRow[]>([]);
  const [userForm, setUserForm] = useState({ displayName: "", email: "", phone: "", role: "salesperson", temporaryPassword: "" });
  const [sheet, setSheet] = useState<SheetState | null>(null);
  const [sheetForm, setSheetForm] = useState({ spreadsheet: "", sheetName: "Leads", headerRow: 1, importAfter: "", enabled: false, mapping: defaultMapping });
  const [store, setStore] = useState<StoreState>({ opensAt: "10:30", closesAt: "20:30", closedWeekdays: [], followupDays: 4 });
  const [meta, setMeta] = useState<MetaState | null>(null);
  const [metaForms, setMetaForms] = useState<MetaForm[]>([]);
  const [message, setMessage] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);

  async function load() {
    const [usersResponse, sheetResponse, storeResponse, metaResponse] = await Promise.all([fetch("/api/admin/users", { cache: "no-store" }), fetch("/api/integrations/google-sheets", { cache: "no-store" }), fetch("/api/settings/store-hours", { cache: "no-store" }), fetch("/api/integrations/meta", { cache: "no-store" })]);
    if (usersResponse.ok) setUsers((await usersResponse.json()).users);
    if (sheetResponse.ok) { const value = await sheetResponse.json() as SheetState; setSheet(value); if (value.connection) setSheetForm({ spreadsheet: value.connection.spreadsheet_id, sheetName: value.connection.sheet_name, headerRow: value.connection.header_row, importAfter: value.connection.import_after?.slice(0,16) ?? "", enabled: value.connection.enabled, mapping: { ...defaultMapping, ...value.connection.mapping } }); }
    if (storeResponse.ok) { const value = await storeResponse.json() as StoreState; setStore({ opensAt: value.opensAt, closesAt: value.closesAt, closedWeekdays: value.closedWeekdays, followupDays: value.followupDays }); }
    if (metaResponse.ok) { const value = await metaResponse.json() as MetaState; setMeta(value); setMetaForms(value.forms); }
  }
  useEffect(() => { void load(); }, []);

  async function addUser(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const response = await fetch("/api/admin/users", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(userForm) }); const value = await response.json() as { error?: string }; setMessage(response.ok ? "User created. They must change the temporary password." : value.error ?? "Could not create user"); if (response.ok) { setUserForm({ displayName: "", email: "", phone: "", role: "salesperson", temporaryPassword: "" }); await load(); } }
  async function updateUser(id: string, body: Record<string, unknown>) { const response = await fetch(`/api/admin/users/${id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); const value = await response.json() as { error?: string }; setMessage(response.ok ? "User updated" : value.error ?? "Could not update user"); if (response.ok) await load(); }
  async function resetPassword(id: string) { const temporaryPassword = window.prompt("Enter a temporary password (minimum 10 characters)"); if (temporaryPassword) await updateUser(id, { temporaryPassword }); }

  async function sheetAction(action: "save" | "test" | "sync") { setBusy(true); const endpoint = action === "save" ? "/api/integrations/google-sheets" : `/api/integrations/google-sheets/${action}`; const payload = { ...sheetForm, importAfter: sheetForm.importAfter ? new Date(sheetForm.importAfter).toISOString() : undefined }; const response = await fetch(endpoint, { method: action === "save" ? "PUT" : "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); const value = await response.json() as Record<string, unknown>; setMessage(response.ok ? action === "test" ? `Connected: ${value.rowCount} rows found.` : action === "sync" ? `${value.inserted} new, ${value.repeats} repeats, ${value.unchanged} unchanged, ${value.skipped} skipped.` : "Google Sheet settings saved" : String(value.error ?? "Google Sheet action failed")); setBusy(false); if (response.ok) await load(); }
  async function saveStore(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const response = await fetch("/api/settings/store-hours", { method: "PUT", headers: { "content-type": "application/json" }, body: JSON.stringify(store) }); const value = await response.json() as { error?: string }; setMessage(response.ok ? "Store hours and cadence saved" : value.error ?? "Could not save hours"); }
  async function metaAction(action: "save" | "test") { setBusy(true); const response = await fetch(action === "save" ? "/api/integrations/meta" : "/api/integrations/meta/test", { method: action === "save" ? "PUT" : "POST", headers: { "content-type": "application/json" }, body: action === "save" ? JSON.stringify({ forms: metaForms }) : undefined }); const value = await response.json() as Record<string, unknown>; setMessage(response.ok ? action === "save" ? "Meta form settings saved" : `Meta connected as ${String(value.detail ?? "system user")}` : String(value.error ?? "Meta action failed")); setBusy(false); if (response.ok) await load(); }
  function updateMetaForm(index: number, next: MetaForm) { setMetaForms(metaForms.map((form, position) => position === index ? next : form)); }

  return <div className="admin-grid">
    {message && <button className="admin-message" onClick={() => setMessage(null)}><CheckCircle2 />{message}</button>}
    <section className="panel admin-card wide users-card"><header><UsersRound /><div><h2>Users and roles</h2><p>Owner, salesperson and read-only agency access</p></div><span className="healthy-tag">{users.filter((item) => item.status === "active").length} active</span></header>
      <form className="user-create-form" onSubmit={addUser}><label>Name<input required minLength={2} value={userForm.displayName} onChange={(event) => setUserForm({ ...userForm, displayName: event.target.value })} /></label><label>Email<input required type="email" value={userForm.email} onChange={(event) => setUserForm({ ...userForm, email: event.target.value })} /></label><label>Phone (optional)<input value={userForm.phone} onChange={(event) => setUserForm({ ...userForm, phone: event.target.value })} /></label><label>Role<select value={userForm.role} onChange={(event) => setUserForm({ ...userForm, role: event.target.value })}><option value="salesperson">Salesperson</option><option value="owner">Owner</option><option value="agency">Agency viewer</option></select></label><label>Temporary password<input required type="password" minLength={10} value={userForm.temporaryPassword} onChange={(event) => setUserForm({ ...userForm, temporaryPassword: event.target.value })} /></label><button><UserPlus />Create</button></form>
      <div className="user-list">{users.map((item) => <div key={item.id}><span className="person-dot">{item.display_name[0]}</span><span><strong>{item.display_name}</strong><small>{item.role} · {item.email}</small></span><em className={item.status === "active" ? "healthy-tag" : "setup-tag"}>{item.status}</em><button onClick={() => void resetPassword(item.id)}><KeyRound size={14} />Reset password</button><button onClick={() => void updateUser(item.id, { status: item.status === "active" ? "disabled" : "active" })}>{item.status === "active" ? "Disable" : "Enable"}</button></div>)}</div>
    </section>

    <section className="panel admin-card wide"><header><Clock3 /><div><h2>Store clock and follow-ups</h2><p>One seven-day schedule; response time counts business minutes only</p></div></header><form className="store-form" onSubmit={saveStore}><label>Opens<input type="time" value={store.opensAt} onChange={(event) => setStore({ ...store, opensAt: event.target.value })} /></label><label>Closes<input type="time" value={store.closesAt} onChange={(event) => setStore({ ...store, closesAt: event.target.value })} /></label><label>Follow-up days<input type="number" min="1" max="14" value={store.followupDays} onChange={(event) => setStore({ ...store, followupDays: Number(event.target.value) })} /></label><fieldset><legend>Closed days</legend>{["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].map((day,index) => <label key={day}><input type="checkbox" checked={store.closedWeekdays.includes(index)} onChange={(event) => setStore({ ...store, closedWeekdays: event.target.checked ? [...store.closedWeekdays,index] : store.closedWeekdays.filter((value) => value !== index) })} />{day}</label>)}</fieldset><button><Save />Save schedule</button></form></section>

    <section id="google-sheet-intake" className="panel admin-card wide sheets-card"><header><FileSpreadsheet /><div><h2>Live Google Sheet intake</h2><p>Incremental sync, periodic full check and no row limit</p></div><span className={sheet?.credentialsConfigured ? "healthy-tag" : "setup-tag"}>{sheet?.credentialsConfigured ? "Credentials ready" : "Setup required"}</span></header>{sheet && !sheet.credentialsConfigured && <p className="sheet-error">The Sheet is saved, but syncing cannot start until the deployment team adds the Google service-account email and private key on the server.</p>}<p className="admin-note">Share the Sheet as Viewer with <strong>{sheet?.serviceAccountEmail ?? "the service-account email shown here after server setup"}</strong>. The cutoff prevents historic rows from entering the live queue.</p><div className="sheet-form"><label className="wide-field">Google Sheets URL or ID<input value={sheetForm.spreadsheet} onChange={(event) => setSheetForm({ ...sheetForm, spreadsheet: event.target.value })} /></label><label>Tab<input value={sheetForm.sheetName} onChange={(event) => setSheetForm({ ...sheetForm, sheetName: event.target.value })} /></label><label>Header row<input type="number" min="1" value={sheetForm.headerRow} onChange={(event) => setSheetForm({ ...sheetForm, headerRow: Number(event.target.value) })} /></label><label>Import leads created after<input type="datetime-local" value={sheetForm.importAfter} onChange={(event) => setSheetForm({ ...sheetForm, importAfter: event.target.value })} /></label>{Object.entries(sheetForm.mapping).map(([key,value]) => <label key={key}>{key.replace(/([A-Z])/g," $1")} column<input value={value} onChange={(event) => setSheetForm({ ...sheetForm, mapping: { ...sheetForm.mapping, [key]: event.target.value } as Mapping })} /></label>)}<label className="sheet-toggle wide-field"><input type="checkbox" checked={sheetForm.enabled} onChange={(event) => setSheetForm({ ...sheetForm, enabled: event.target.checked })} />Enable automatic sync</label></div><div className="sheet-actions"><button disabled={busy} onClick={() => void sheetAction("save")}><Save />Save</button><button disabled={busy || !sheet?.credentialsConfigured} onClick={() => void sheetAction("test")}><CheckCircle2 />Test</button><button disabled={busy || !sheet?.connection?.enabled || !sheet?.credentialsConfigured} onClick={() => void sheetAction("sync")}><RefreshCw />Sync now</button></div>{sheet?.connection && <p className="admin-note">Last sync: {sheet.connection.last_synced_at ? new Date(sheet.connection.last_synced_at).toLocaleString("en-IN") : "never"} · Last cutoff skips: {sheet.connection.last_skipped_rows}</p>}{sheet?.runs?.length ? <div className="sync-history">{sheet.runs.map((run) => <span key={run.id}>{new Date(run.started_at).toLocaleString("en-IN")} · {run.status} · {run.inserted_rows} new · {run.repeat_rows} repeat · {run.skipped_rows} skipped · {run.unchanged_rows} unchanged</span>)}</div> : null}</section>

    <section className="panel admin-card wide"><header><Radio /><div><h2>Meta Lead Ads</h2><p>Signed webhooks plus a 15-minute two-hour reconciliation window</p></div><span className={meta?.enabledByEnvironment && meta?.credentialsConfigured ? "healthy-tag" : "setup-tag"}>{meta?.enabledByEnvironment ? meta?.credentialsConfigured ? "Enabled" : "Credentials needed" : "Off on server"}</span></header><p className="admin-note">Credentials stay on the server and are never saved here or sent to this browser. Graph API: <strong>{meta?.graphVersion ?? "—"}</strong> · Last webhook: <strong>{meta?.connection?.last_webhook_at ? new Date(meta.connection.last_webhook_at).toLocaleString("en-IN") : "never"}</strong> · Last reconciliation: <strong>{meta?.connection?.last_reconciled_at ? new Date(meta.connection.last_reconciled_at).toLocaleString("en-IN") : "never"}</strong></p>
      <div className="sync-history">{metaForms.map((form,index) => <div className="sheet-form" key={`${form.formId}-${index}`}><label>Form ID<input required value={form.formId} onChange={(event) => updateMetaForm(index,{ ...form,formId:event.target.value })} /></label><label>Label<input required value={form.name} onChange={(event) => updateMetaForm(index,{ ...form,name:event.target.value })} /></label>{Object.entries(form.mapping).map(([key,value]) => <label key={key}>{key} field<input value={value} onChange={(event) => updateMetaForm(index,{ ...form,mapping:{ ...form.mapping,[key]:event.target.value } })} /></label>)}<button aria-label="Remove form" onClick={() => setMetaForms(metaForms.filter((_,position) => position !== index))}><Trash2 size={16} />Remove</button></div>)}</div>
      <div className="sheet-actions"><button onClick={() => setMetaForms([...metaForms,newMetaForm()])}><Plus />Add form</button><button disabled={busy || metaForms.some((form) => !form.formId || !form.name)} onClick={() => void metaAction("save")}><Save />Save forms</button><button disabled={busy || !meta?.credentialsConfigured} onClick={() => void metaAction("test")}><CheckCircle2 />Test connection</button></div>
      {meta?.connection?.last_reconciliation_result && <p className="admin-note">Latest result: {JSON.stringify(meta.connection.last_reconciliation_result)}</p>}
    </section>
  </div>;
}
